apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jumpbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: jumpbox
        image: localhost:5000/jumpbox
        command:
          - sleep
          - "3600"